# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/amber/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),amber)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,25110551782c39ae345ff47f52f099c3a137e276)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,36ebe374597de78182e3305ed87a63c6ff1f3869)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,2be09d28c7003dfda1898e21a49602ea2bf2a8bc)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,cd4486798fb7161e210c961ba5af4afa633c5958)
$(call add-radio-file-sha1-checked,radio/dpm.img,23da861e82fb5dff3b0aa05e99876fcd24a0f111)
$(call add-radio-file-sha1-checked,radio/gz.img,ca92df7f76569fe757eb665f29d0d3a839ac1c65)
$(call add-radio-file-sha1-checked,radio/lk.img,78ba3803ae0b03fe22be13a2816680ddeb0d8332)
$(call add-radio-file-sha1-checked,radio/logo.img,e2f4fdad545afc796368a0d294d621c4a391f350)
$(call add-radio-file-sha1-checked,radio/mcupm.img,f4dd618f9bfa15788ab42a9c6cb3897f6d43282a)
$(call add-radio-file-sha1-checked,radio/md1img.img,5451d4356343f8df58f0eb2d346916700b31fe0c)
$(call add-radio-file-sha1-checked,radio/pi_img.img,90c2c4816f64f73c93d57843428c854368534f61)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,d4b204b899e83ba9662728cca7ebb14ff32e7d7f)
$(call add-radio-file-sha1-checked,radio/scp.img,b3d622bffc98692310c96474eaf42d217aab23d5)
$(call add-radio-file-sha1-checked,radio/spmfw.img,3ad636985236ed076e8a8b0973d24428a5b51130)
$(call add-radio-file-sha1-checked,radio/sspm.img,70900beaa59defa4aa3bbcc7a8326f7ed53c6831)
$(call add-radio-file-sha1-checked,radio/tee.img,0cd4e8f3e5645783d977d9dd3f99a2f8ab57e8a4)

endif
