# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/amber/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),amber)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,288b27e78eb85bb612e5ce20cc8e8c635395131c)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,165ea2a19654d648134dc7e4c39a49272d479641)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,da8e47a55d5baa96fb8724449242e3998eb97336)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,9a7f8016167a46cfe0cf45eae43c9ffda0a40373)
$(call add-radio-file-sha1-checked,radio/dpm.img,6b68c3a748fe106eec08463100ee6076ead26395)
$(call add-radio-file-sha1-checked,radio/gz.img,df320ff79061006a7f2cacb80162b71bca67d79e)
$(call add-radio-file-sha1-checked,radio/lk.img,95859a83227d33a34ad9b82f44fe2ad5721b9a90)
$(call add-radio-file-sha1-checked,radio/logo.img,c0d6f20ae8bddb93259c3666a575ecf45eb298a8)
$(call add-radio-file-sha1-checked,radio/mcupm.img,6d934902af52498f8adfa32a535a1cfdcfb00c5d)
$(call add-radio-file-sha1-checked,radio/md1img.img,91b0432d99d4787cdb4ee302d3875a6a9f0b18b4)
$(call add-radio-file-sha1-checked,radio/pi_img.img,1f78899a8900f00285916102efee5e7301920ae2)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,5be26fd3cfa2f7a406da0dde7cc12038664bb057)
$(call add-radio-file-sha1-checked,radio/scp.img,87caacb4fdcdbbb02b769b0972123602f79f701a)
$(call add-radio-file-sha1-checked,radio/spmfw.img,a518fd0180e09e6ec00eca7f369455718f47ddbc)
$(call add-radio-file-sha1-checked,radio/sspm.img,33475271c0144246a7311a4d19c2d5bac40b4b16)
$(call add-radio-file-sha1-checked,radio/tee.img,ec65e9e871232923c965e86b20c2b8353f8e81e0)

endif
