# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/amber/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),amber)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,ca62e830c5253f872b19f9148f2963c83e88f580)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,0d91ef6a0587f0c1399cf0fb8600032785765896)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,4a425d45802accf814fc689826a8b5123a7b1a36)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,b5418ce503c23d90b1bbccf16dcd32b5d86d111a)
$(call add-radio-file-sha1-checked,radio/dpm.img,02fa91a3c2c51d3d7e191ca0839332a6ad679147)
$(call add-radio-file-sha1-checked,radio/gz.img,deb8ab3a2d3bb905292f8de45ed04c33e521fbcd)
$(call add-radio-file-sha1-checked,radio/lk.img,0495b8d4dd4e3af10f1918f49958547583d36839)
$(call add-radio-file-sha1-checked,radio/logo.img,0ab9e5cfd5a0d33e0a10b7988bb3048034fb633b)
$(call add-radio-file-sha1-checked,radio/mcupm.img,410da381169567da01d5e90617b9b8b2c6667aa0)
$(call add-radio-file-sha1-checked,radio/md1img.img,2d5d2bf04dc0f9a409049f3e0923b323ba32bc63)
$(call add-radio-file-sha1-checked,radio/pi_img.img,332d0a559c1f78df8ae8b4200b7270e3f0d8acf7)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,9be94c6689383e506e18aa4aa42d6592984945f3)
$(call add-radio-file-sha1-checked,radio/scp.img,ef3af9190a7d5d42b2c8dee9a9facb1be59723c3)
$(call add-radio-file-sha1-checked,radio/spmfw.img,c25724fe88a86e44400ed28a30e363c52a7c9ba1)
$(call add-radio-file-sha1-checked,radio/sspm.img,489182ddcc55e53f0b1e78797d11e7f7ddcdf368)
$(call add-radio-file-sha1-checked,radio/tee.img,9add3b22b070d7cc35c855d2b788bec69cf2ecdb)

endif
