# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/amber/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    audio_dsp \
    cam_vpu1 \
    cam_vpu2 \
    cam_vpu3 \
    dpm \
    gz \
    lk \
    logo \
    mcupm \
    md1img \
    pi_img \
    preloader_raw \
    scp \
    spmfw \
    sspm \
    tee
